# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APP_ID = 'hj.live.app'
TEAM = 'GW9Q5Y27Y2'
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = 'pfgy-sfte-qjik-rrsn'

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Sample.xcodeproj")
    build_app(scheme: "Sample")
    upload_to_testflight
  end
  lane :build do |options|
    increment_build_number(xcodeproj: "Sample.xcodeproj")
    match(
      type: 'appstore',
      force_for_new_devices: true,
      app_identifier: APP_ID,
      readonly: true
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => APP_ID,
      :DEVELOPMENT_TEAM => TEAM
    }

    gym(
      xcargs: settings_to_override,
      clean: true,
      configuration: "Release",
      export_method: 'app-store',
      scheme: "Sample",
      output_directory: "ipa"
    )
    #upload_to_testflight
  end
end
